### ISSUE TITLE
黑群晖docker运行容器提示500错误

### ISSUE THREAD

**Issue by SeanSuny** [a76yyyy/qd#2]
错误日志如下：
2021-08-20 03:44:34	stdout	[31m[E 210820 11:44:34 web:2239](B[m 500 GET / (172.17.0.1) 1.38ms
2021-08-20 03:44:34	stdout	[31m[E 210820 11:44:34 web:2239](B[m 500 GET / (172.17.0.1) 1.38ms
2021-08-20 03:44:34	stdout	    KeyError: 'role'
2021-08-20 03:44:34	stdout	        user['isadmin'] = 'admin' in user['role'] if user['role'] else False
2021-08-20 03:44:34	stdout	      File "/usr/src/app/web/handlers/base.py", line 79, in get_current_user
2021-08-20 03:44:34	stdout	        self._current_user = self.get_current_user()
2021-08-20 03:44:34	stdout	      File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1340, in current_user
2021-08-20 03:44:34	stdout	        user = self.current_user
2021-08-20 03:44:34	stdout	      File "/usr/src/app/web/handlers/base.py", line 52, in prepare
2021-08-20 03:44:34	stdout	        result = self.prepare()
2021-08-20 03:44:34	stdout	      File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1681, in _execute
2021-08-20 03:44:34	stdout	    Traceback (most recent call last):
2021-08-20 03:44:34	stdout	    HTTPServerRequest(protocol='http', host='192.168.8.7:8923', method='GET', uri='/', version='HTTP/1.1', remote_ip='172.17.0.1')
2021-08-20 03:44:34	stdout	[31m[E 210820 11:44:34 web:1789](B[m Uncaught exception GET / (172.17.0.1)
2021-08-20 03:44:34	stdout	    KeyError: 'role'
2021-08-20 03:44:34	stdout	        user['isadmin'] = 'admin' in user['role'] if user['role'] else False
2021-08-20 03:44:34	stdout	      File "/usr/src/app/web/handlers/base.py", line 79, in get_current_user
2021-08-20 03:44:34	stdout	        self._current_user = self.get_current_user()
2021-08-20 03:44:34	stdout	      File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1340, in current_user
2021-08-20 03:44:34	stdout	        user = self.current_user
2021-08-20 03:44:34	stdout	      File "/usr/src/app/web/handlers/base.py", line 52, in prepare
2021-08-20 03:44:34	stdout	        result = self.prepare()
2021-08-20 03:44:34	stdout	      File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1681, in _execute
2021-08-20 03:44:34	stdout	    Traceback (most recent call last):
2021-08-20 03:44:34	stdout	    HTTPServerRequest(protocol='http', host='192.168.8.7:8923', method='GET', uri='/', version='HTTP/1.1', remote_ip='172.17.0.1')
2021-08-20 03:44:34	stdout	[31m[E 210820 11:44:34 web:1789](B[m Uncaught exception GET / (172.17.0.1)

**Comment by a76yyyy** [comment]
是否还未设置管理员账户

**Comment by a76yyyy** [comment]
请检查是否同时运行新旧版签到框架容器

**Comment by SeanSuny** [comment]
第一次启动就提示500 错误，没有办法创建用户，如何设置管理员
旧版容器已经停止运行了

**Comment by a76yyyy** [comment]
1. 旧版容器停止后重启一下群晖，重新映射一个新的数据库目录地址，看是否能运行全新的签到框架；
2. 如果可以运行，停止新版框架容器，将旧版框架的数据库cp到新版数据库所在地址，再启动容器，看能否运行

**Comment by SeanSuny** [comment]
好的 我试试

**Comment by SeanSuny** [comment]
不行还是500错误
群晖容器日志：
2021-09-02 10:14:06 | stdout | [31m[E 210902 18:14:06 web:2239](B[m 500 GET / (172.17.0.1) 14.03ms
-- | -- | --
2021-09-02 10:14:06 | stdout | [31m[E 210902 18:14:06 web:2239](B[m 500 GET / (172.17.0.1) 14.03ms
2021-09-02 10:14:06 | stdout | KeyError: 'role'
2021-09-02 10:14:06 | stdout | user['isadmin'] = 'admin' in user['role'] if user['role'] else False
2021-09-02 10:14:06 | stdout | File "/usr/src/app/web/handlers/base.py", line 79, in get_current_user
2021-09-02 10:14:06 | stdout | self._current_user = self.get_current_user()
2021-09-02 10:14:06 | stdout | File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1340, in current_user
2021-09-02 10:14:06 | stdout | user = self.current_user
2021-09-02 10:14:06 | stdout | File "/usr/src/app/web/handlers/base.py", line 52, in prepare
2021-09-02 10:14:06 | stdout | result = self.prepare()
2021-09-02 10:14:06 | stdout | File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1681, in _execute
2021-09-02 10:14:06 | stdout | Traceback (most recent call last):
2021-09-02 10:14:06 | stdout | HTTPServerRequest(protocol='http', host='192.168.8.7:8923', method='GET', uri='/', version='HTTP/1.1', remote_ip='172.17.0.1')
2021-09-02 10:14:06 | stdout | [31m[E 210902 18:14:06 web:1789](B[m Uncaught exception GET / (172.17.0.1)
2021-09-02 10:14:06 | stdout | KeyError: 'role'
2021-09-02 10:14:06 | stdout | user['isadmin'] = 'admin' in user['role'] if user['role'] else False
2021-09-02 10:14:06 | stdout | File "/usr/src/app/web/handlers/base.py", line 79, in get_current_user
2021-09-02 10:14:06 | stdout | self._current_user = self.get_current_user()
2021-09-02 10:14:06 | stdout | File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1340, in current_user
2021-09-02 10:14:06 | stdout | user = self.current_user
2021-09-02 10:14:06 | stdout | File "/usr/src/app/web/handlers/base.py", line 52, in prepare
2021-09-02 10:14:06 | stdout | result = self.prepare()
2021-09-02 10:14:06 | stdout | File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1681, in _execute
2021-09-02 10:14:06 | stdout | Traceback (most recent call last):
2021-09-02 10:14:06 | stdout | HTTPServerRequest(protocol='http', host='192.168.8.7:8923', method='GET', uri='/', version='HTTP/1.1', remote_ip='172.17.0.1')
2021-09-02 10:14:06 | stdout | [31m[E 210902 18:14:06 web:1789](B[m Uncaught exception GET / (172.17.0.1)
2021-09-02 10:13:37 | stdout | [32m[I 210902 18:13:37 run:54](B[m http server started on 0.0.0.0:80

**Comment by a76yyyy** [comment]
删除所有新版框架容器，停止旧版容器后直接运行这条命令呢？
`docker run -d --name qiandao -p 8923:80 a76yyyy/qiandao`
也就是不映射数据库地址

**Comment by SeanSuny** [comment]
一样的错误尴尬了

**Comment by a76yyyy** [comment]
QQ:1224618144 你加我远程调试看一下吧

**Comment by Sean-007** [comment]
向日葵吧 我的识别码: 229822410

**Comment by a76yyyy** [comment]
框架容器已更新，请重新拉取

**Comment by a76yyyy** [comment]
问题源于新旧框架的浏览器缓存冲突问题，当前已修复
